# Generated by Django 4.2.3 on 2023-07-21 10:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
